baseURL: https://masputrawae.github.io/
languageCode: id
title: My Notes
timeZone: Asia/Jakarta
enableEmoji: true

mediaType: 'application/json'
outputFormats:
  search:
    mediaType: 'application/json'
    baseName: 'search'
    isPlainText: true
    notAlternative: true

  manifest:
    mediaType            : 'application/json'
    baseName             : 'manifest'
    isPlainText          : true
    notAlternative       : true

  random-page:
    mediaType            : 'text/html'
    baseName             : 'random-page'
    isPlainText          : true
    notAlternative       : true

outputs:
  home:
    - html
    - rss
    - sitemap
    - random-page
    - search
    - manifest
